import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getInitData } from "@/lib/api";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getInitData();

  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="allbox">
          <Header siteName={data.profile.SITE_NAME} menu={data.modules} />
          <main>{children}</main>
          <Footer siteName={data.profile.SITE_NAME} menu={data.modules} />
        </div>
      </body>
    </html>
  );
}
